## Dictionaries

In [346]:
## creating dictionaries

empty_dict = {}
print(type(empty_dict))

<class 'dict'>

In [347]:
empty_dict = dict()
empty_dict

{}

In [348]:
student = {"name":"alireza", "age":42, "grade": 89}
print(student)
print(type(student))

{'name': 'alireza', 'age': 42, 'grade': 89}
<class 'dict'>

In [349]:
## single key is always used
student = {"name":"alireza", "age":42, "name": 89}
print(student)

{'name': 89, 'age': 42}

In [350]:
## accessing dictionary elements
student = {"name":"alireza", "age":42, "grade": "A"}
print(student)

{'name': 'alireza', 'age': 42, 'grade': 'A'}

In [351]:
print(student['grade'])
print(student['age'])

A
42

In [352]:
## accessing using get() method
print(student.get('grade'))
print(student.get('last_name'))

A
None

In [353]:
## modifying dictionary elements

print(student)

{'name': 'alireza', 'age': 42, 'grade': 'A'}

In [354]:
student["age"] = 33 ## updated value for the key
print(student)
student["address"]= "India"  ## added a new key and value
print(student)

{'name': 'alireza', 'age': 33, 'grade': 'A'}
{'name': 'alireza', 'age': 33, 'grade': 'A', 'address': 'India'}

In [355]:
## delete the key

del student['grade']
print(student)

{'name': 'alireza', 'age': 33, 'address': 'India'}

In [356]:
## dictionary methods

keys = student.keys()  ## get all the keys
print(keys)
values = student.values()  ## get all the values
print(values)

items = student.items()  ## get all key values
print(items)

dict_keys(['name', 'age', 'address'])
dict_values(['alireza', 33, 'India'])
dict_items([('name', 'alireza'), ('age', 33), ('address', 'India')])

In [357]:
## shallow copy

student_copy = student
print(student)
print(student_copy)

{'name': 'alireza', 'age': 33, 'address': 'India'}
{'name': 'alireza', 'age': 33, 'address': 'India'}

In [358]:
student["name"] = "krish"
print(student)
print(student_copy)

{'name': 'krish', 'age': 33, 'address': 'India'}
{'name': 'krish', 'age': 33, 'address': 'India'}

In [359]:
student_copy1 = student.copy()   ## shallow copy
print(student_copy1)
print(student)

{'name': 'krish', 'age': 33, 'address': 'India'}
{'name': 'krish', 'age': 33, 'address': 'India'}

In [360]:
student["name"] = "Tom"
print(student_copy1)
print(student)

{'name': 'krish', 'age': 33, 'address': 'India'}
{'name': 'Tom', 'age': 33, 'address': 'India'}

In [361]:
## iterating over dictionaries

## iterating over keys

for key in student.keys():
    print(key)

name
age
address

In [362]:
## iterate over values
for value in student.values():
    print(value)

Tom
33
India

In [363]:
## iterate over values
for key,value in student.items():
    print(f"{key}: {value}")

name: Tom
age: 33
address: India

In [364]:
## Nested dictionaries

students = {
    "student1" : {"name": "ali", "age": 32},
    "student2" : {"name":"John", "age": 55}

}

print(students)

{'student1': {'name': 'ali', 'age': 32}, 'student2': {'name': 'John', 'age': 55}}

In [365]:
## access nested dictionaries elements

print(students["student2"]["name"])
print(students["student2"]["age"])

John
55

In [366]:
students.items()

dict_items([('student1', {'name': 'ali', 'age': 32}), ('student2', {'name': 'John', 'age': 55})])

In [367]:
## iterating over nested dictionaries
for student_id, student_info in students.items():
    print(f"{student_id}: {student_info}")
    for key,value in student_info.items():
        print(f"{key}:{value}")

student1: {'name': 'ali', 'age': 32}
name:ali
age:32
student2: {'name': 'John', 'age': 55}
name:John
age:55

#### Dictionary comprehension

In [368]:
squares = {x:x**2 for x in range(5)}
print(squares)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

In [369]:
## conditional dictionary comprehension

evens = {x:x**2 for x in range(10) if x%2 == 0}
print(evens)

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}

In [370]:
## practical examples

## use adictionary to count the frequency of elements in list

numbers = [1,2,2,3,3,3,4,4,4,4]

frequency = {}

for number in numbers:
    if number in frequency:
        frequency[number]+=1
    else:
        frequency[number] = 1

print(frequency)

{1: 1, 2: 2, 3: 3, 4: 4}

In [371]:
## merge 2 dictionaries into one

dict1 = {"a": 1, "b": 2}
dict2 = {"b": 3, "c": 4}

merged_dict = {**dict1, **dict2}
print(merged_dict)

{'a': 1, 'b': 3, 'c': 4}

## Function

In [372]:
## shy functions?

num = 24
if num%2 ==0:
    print("the number is even")
else:
    print("the number is odd")

the number is even

In [373]:
def even_or_odd(num):
    """This function finds even or odd"""
    if num%2 == 0:
        print("the number is even")
    else:
        print("the number is odd")

In [374]:
## call the function
even_or_odd(7)

the number is odd

In [375]:
## function with multiple parameters

def add(a,b):
    return a +b

result = add(2,4)
print(result)

6

In [376]:
## default parameters

def greet(name = "Guest"):
    print(f"Hello {name} welcome to the paradise")

greet()

Hello Guest welcome to the paradise

In [377]:
greet("Alireza")

Hello Alireza welcome to the paradise

In [378]:
## variable length arguments
## positional and keywords arguments

def print_numbers(*ali):
    for number in ali:
        print(number)

print_numbers(1,2,3,4,5,6,7, "ali")  ## these parameters called positional arguments

1
2
3
4
5
6
7
ali

In [379]:
## best practice for positional arguments
def print_numbers(*args):
    for number in args:
        print(number)

print_numbers(1,2,3,4,5,6,7, "ali")  ## these parameters called positional arguments

1
2
3
4
5
6
7
ali

In [380]:
## keywords arguments

def print_details(**kwargs):
    for key,value in kwargs.items():
        print(f"{key} : {value}")

In [381]:
print_details(name = "alireza", age = 43, country = "Netherlands")

name : alireza
age : 43
country : Netherlands

In [382]:
def print_details(*args, **kwargs):
    for val in args:
        print(f"Positional argument : {val}")
    for key,value in kwargs.items():
        print(f"{key} : {value}")

In [383]:
print_details(1,2,3,4,5,6,7, "ali", name = "alireza", age = 43, country = "Netherlands")

Positional argument : 1
Positional argument : 2
Positional argument : 3
Positional argument : 4
Positional argument : 5
Positional argument : 6
Positional argument : 7
Positional argument : ali
name : alireza
age : 43
country : Netherlands

In [384]:
### return statements
def multiply(a,b):
    return a*b

multiply(2,3)

6

In [385]:
### return multiple parameters
def multiply(a,b):
    return a*b,a

multiply(2,3)

(6, 2)

## Function Examples

In [386]:
## temperature conversion

def convert_temperature(temp, unit):

    """This function converts temperature between celcius and fahrenheit"""
    if unit =='C':
        return temp * (9/4) +32  ## celcius to fahrenheit
    elif unit == 'F':
        return (temp - 32) * 5/9  ## fahrenheit to celcius
    else:
        return None


print(convert_temperature(45, 'C'))
print(convert_temperature(79, 'F'))

133.25
26.11111111111111

In [387]:
## password strength checker

def is_strong_password(password):
    """This function checks if the password is strong or not"""
    if len(password) < 8:
        return False
    if not any(char.isdigit() for char in password):
        return False
    if not any(char.islower() for char in password):
        return False
    if not any(char.isupper() for char in password):
        return False
    if not any(char in '^[a-zA-Z0-9 ]+$' for char in password):
        return False
    return True

## calling the function
print(is_strong_password("wek@TT 122T"))

True

In [388]:
## calculate the total cost of items in a shopping cart

def calculate_total_cost(cart):
    total_cost = 0
    for item in cart:
        total_cost += item['price'] * item['quantity']

    return total_cost

## Example cart data

cart = [
    {'name':'Apple', 'price': 0.5, 'quantity': 4},
    {'name': 'Banana', 'price':0.3, 'quantity':6},
    {'name': 'Orange', 'price':0.7, 'quantity':3}
]

## calling the function
total_cost = calculate_total_cost(cart)
print(total_cost)

5.8999999999999995

In [389]:
## check if a string is palindrome

def is_palindrome(s):
    s = s.lower().replace(" ","")
    return s == s[::-1]  ## get the reverse of string

print(is_palindrome("A man a plan a canal Panama"))

print("hello")

True
hello

In [390]:
## calculate the factorial of a number using recursion

def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

print(factorial(6))

720

In [391]:
## a function to raed a file and count the frequency of each word

def count_word_frequency(file_path):
    word_count={}
    with open(file_path, 'r') as file:
        for line in file:
            words= line.split()
            for word in words:
                word = word.lower().strip('.,!?;:"\'')
                word_count[word] = word_count.get(word, 0) + 1
    
    return word_count


file_path = 'sample.txt'
word_frequency = count_word_frequency(file_path)
print(word_frequency)

{'hello': 1, 'world': 1, 'how': 1, 'are': 1, 'you': 1, 'my': 1, 'name': 1, 'is': 1, 'krish': 1}

In [392]:
## function to check a valid email

import re

# Email validation function
def is_valid_email(email):
    """This function checks if the email is valid."""
    
    pattern = r'^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$'
    
    return re.match(pattern, email) is not None


# Calling the function
print(is_valid_email("test@example.com"))  # Output: True
print(is_valid_email("invalid-email"))      # Output: False

True
False

### Lambda function in Python

In [393]:
### syntax  
lambda arguments: expression

In [394]:
def addition(a,b):
    return a + b

In [395]:
addition(2,5)

7

In [396]:
addition = lambda a,b: a+b
print(type(addition))
print(addition(3,5))

<class 'function'>
8

In [397]:
def even(num):
    if num%2 ==0:
        return True

even(56)

True

In [398]:
even1 = lambda num:num%2 == 0
even1(6)

True

In [399]:
def addition(x,y,z):
    return x+y+z

addition(3,7,9)

19

In [400]:
addition = lambda x,y,z:x+y+z

addition(3,5,8)

16

In [401]:
## map()   applies a function to all items in a list

numbers = [1,2,3,4,5,6]

def square(number):
    return number**2

square(2)

4

In [402]:
list(map(lambda x:x**2, numbers))

[1, 4, 9, 16, 25, 36]

In [403]:
def square(x):
    return x*x

square(5)

25

In [404]:
numbers = [1,2,3,4,5,6,7,8]

map(square, numbers)  ## create an object

In [405]:
list(map(square, numbers))

[1, 4, 9, 16, 25, 36, 49, 64]

In [406]:
## lambda function with map
numbers = [1,2,3,4,5,6,7,8]
list(map(lambda x:x**2, numbers))

[1, 4, 9, 16, 25, 36, 49, 64]

In [407]:
## map multiple iterables

numbers1 = [1,2,3]
numbers2 = [4,5,6]

added_numbers = list(map(lambda x,y:x+y, numbers1,numbers2))
print(added_numbers)

[5, 7, 9]

In [408]:
## map() to convert a list of string to integers

str_numbers=['1','2','3','4','5']
int_numbers = list(map(int , str_numbers))

print(int_numbers)

[1, 2, 3, 4, 5]

In [409]:
words = ['apple', 'banana', 'cherry']

upper_words = list(map(str.upper, words))
print(upper_words)

['APPLE', 'BANANA', 'CHERRY']

In [410]:
def get_name(person):  ## this function is good for a dictionary and not for a list of dictionaries
    return person['name']

people = [
    {'name': 'Krish', 'age':43},
    {'name':'Jack', 'age' : 32}
]

list(map(get_name,people))

['Krish', 'Jack']

### Filter function in Python

In [411]:
def even(num):
    if num%2 == 0:
        return True

In [412]:
even(4)

True

In [413]:
lst = [1,2,3,4,5,6,7,8,9,10,11,12]

list(filter(even, lst))

[2, 4, 6, 8, 10, 12]

In [414]:
## filter with a lambda function

numbers = [1,2,3,4,5,6,7,8,9]

greater_than_five = list(filter(lambda x:x>5, numbers))

print(greater_than_five)

[6, 7, 8, 9]

In [415]:
## filter with a lambda function and multiple condition

numbers = [1,2,3,4,5,6,7,8,9]
even_and_greater_than_five = list(filter(lambda x:x>5 and x%2==0, numbers))
print(even_and_greater_than_five)

[6, 8]

In [416]:
## apply filter() to check is greater than 25 in dictionary

people = [
    {'name': 'Krish', 'age':43},
    {'name':'Jack', 'age' : 22},
    {'name': 'John', 'age': 55}
]

def age_grater_than_25(person):
    return person['age'] > 25

list(filter(age_grater_than_25, people))

[{'name': 'Krish', 'age': 43}, {'name': 'John', 'age': 55}]

## Importing modules and packages in Python

In [417]:
import math

math.sqrt(64)

8.0

In [418]:
from math import sqrt,pi

print(sqrt(16))
print(sqrt(25))
print(pi)

4.0
5.0
3.141592653589793

In [419]:
import numpy as np

np.array([1,2,3])

array([1, 2, 3])

In [420]:
from math import *
print(sqrt(16))
print(pi)

4.0
3.141592653589793

In [421]:
from package.maths import addition
addition(2,3)

5

In [422]:
from package import maths
maths.addition(4,5)

9

### Standard library overview

In [423]:
import array

arr = array.array('i', [1,2,3,4])  ## i means the items of this array should be integer
print(arr)

array('i', [1, 2, 3, 4])

In [424]:
import math

print(math.sqrt(16))

4.0

In [425]:
import random
print(random.randint(1,10))
print(random.choice(['apple', 'kiwi', 'banana']))

5
kiwi

In [426]:
## File and ddirectory access

import os
print(os.getcwd())

c:\Users\Gebruiker\Documents\python_mysql_practice_2026

In [427]:
os.mkdir('test_directory')

FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'test_directory'

In [ ]:
import os

os.chdir("package")
print(os.getcwd())

c:\Users\Gebruiker\Documents\python_mysql_practice_2026\package

In [ ]:
## High level operations on files and collection of files
import shutil
shutil.copyfile('source.txt', 'destination.txt')

'destination.txt'

In [ ]:
## Data serialization
import json
data = {'name': 'Alireza', 'age': 35}

json_str = json.dumps(data)  ## The json.dumps() function converts a Python dictionary into a JSON string.
print(json_str)  ## Although the output looks like a dictionary, it is actually a string (str), not a dictionary (dict).
print(type(json_str))

{"name": "Alireza", "age": 35}
<class 'str'>

In [ ]:
parsed_data = json.loads(json_str)
print(parsed_data)
print(type(parsed_data))

{'name': 'Alireza', 'age': 35}
<class 'dict'>

In [ ]:
## csv

import csv
with open('example.csv', mode = 'w', newline = '') as file:
    writer = csv.writer(file)
    writer.writerow(['name', 'age'])
    writer.writerow(['Alireza', 43])

with open('example.csv', mode= 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['name', 'age']
['Alireza', '43']

In [ ]:
## datetime
from datetime import datetime, timedelta

now = datetime.now()
print(now)

2026-10-08 21:54:15.522971

In [ ]:
yesterday = now - timedelta(days = 1)
print(yesterday)

2026-10-07 21:54:15.522971

In [ ]:
## time
import time
print(time.time())
time.sleep(2)
print(time.time())

1791489440.111691
1791489442.112284

In [ ]:
## regular expression

import re

pattern = r'\d+'
text = 'There are 123 apples  456'
match = re.search(pattern, text)
print(match.group())

123

### File operation _read and write

In [ ]:
import os

print(os.getcwd())
print(os.listdir())

c:\Users\Gebruiker\Documents\python_mysql_practice_2026\package
['.ipynb_checkpoints', 'destination.txt', 'example.csv', 'maths.py', 'source.txt', 'subpackages', '__init__.py', '__pycache__']

In [ ]:
os.chdir('6.file_handeling/')
print(os.getcwd())

c:\Users\Gebruiker\Documents\python_mysql_practice_2026\6.file_handeling

In [ ]:
## read a whole file

with open('example.txt', mode = 'r') as file:
    content = file.read()
    print(content)

Hello how are you?
I am good
My name is Alireza
Welcome to teh class

In [ ]:
## read a file line by line

with open('example.txt', 'r') as file:
    for line in file:
        print(line.strip())  ## strip() removes the newline character

Hello how are you?
I am good
My name is Alireza
Welcome to teh class

In [ ]:
## writing a file(overwriting)

with open('example.txt', 'w') as file:
    file.write('Hello everyone!\n')
    file.write('This is a new line.')

In [ ]:
## Write a file without overwriting
with open('example.txt', 'a') as file:
    file.write("Append some place!\n")

In [ ]:
## writing a list of lines to a file

lines = ['first line \n', 'second line \n', 'third line \n']
with open('example.txt', 'a') as file:
    file.writelines(lines)

In [ ]:
## Binary files

## writing a binary files
data = b'\x00\x01\x02\x03\x04'
with open('example.bin', 'wb') as file:
    file.write(data)

In [ ]:
## reading a binary file
with open('example.bin', 'rb') as file:
    content = file.read()
    print(content)

b'\x00\x01\x02\x03\x04'

In [ ]:
## read the content from source text file and write to a distination text file

with open('example.txt', 'r') as source_file:
    content = source_file.read()
    print(content)

with open('destination.txt', 'w') as destination_file:
    destination_file.write(content)

Hello everyone!
This is a new line.Append some senctences tacke place!Append some senctences tacke place!
Append some place!
first line
second line
third line

In [ ]:
## read a text file and count the number of lines, words and characters
# Counting lines, words, and characters in a text file

def count_text_file(file_path):
    with open(file_path, 'r') as file:
        lines = file.readlines()
        line_count = len(lines)
        word_count = sum(len(line.split()) for line in lines)
        char_count = sum(len(line) for line in lines)

    return line_count, word_count, char_count


file_path = 'example.txt'

lines, words, characters = count_text_file(file_path)

print(f'Lines: {lines}, Words: {words}, Characters: {characters}')

Lines: 6, Words: 24, Characters: 162

In [ ]:
## writing and then raeding a file

with open('example.txt', 'w+') as file:
    file.write("Hello world \n")
    file.write("This is a new line \n")

    ## move the file cursor to the begining
    file.seek(0)

    ## rread the content of the file
    content = file.read()
    print(content)

Hello world
This is a new line

### Working with file path

In [ ]:
## create a new directory

new_directory = "package"
os.mkdir(new_directory)
print(f"Directory '{new_directory}' create")

Directory 'package' create

In [ ]:
## listing files and directories

items = os.listdir('.')  ## dot means we looking at current folder
print(items)

['destination.txt', 'example.bin', 'example.txt', 'package']

In [ ]:
### Joing paths

dir_name = "folder"
file_name = "file.txt"
full_path = os.path.join(dir_name, file_name)
print(full_path)

folder\file.txt

In [ ]:
dir_name = "folder"
file_name = "file.txt"
full_path = os.path.join(os.getcwd(),dir_name, file_name)
print(full_path)

c:\Users\Gebruiker\Documents\python_mysql_practice_2026\6.file_handeling\folder\file.txt

In [ ]:
## checking if a file or directory exists or not

path = 'example2.txt'
if os.path.exists(path):
    print(f"The path '{path} exists'")
else:
    print(f"The path '{path} does not exist")

The path 'example.txt exists'

In [ ]:
## Checking if a path is a file or directory

import os

path = 'example.txt'
if os.path.isfile(path):
    print(f"The path '{path}' is a file.")
elif os.path.isdir(path):
    print(f"The path '{path}' is a directory.")
else:
    print(f"The path '{path}' is  niether a file nor a directory.")

The path 'example.txt' is a file.

In [ ]:
## Getting the absolute path

relative_path = 'example.txt'
absolute_path = os.path.abspath(relative_path)
print(absolute_path)

c:\Users\Gebruiker\Documents\python_mysql_practice_2026\6.file_handeling\example.txt

## Exceptions in Python

In [ ]:
## Exception   try, except, block
try:
    a = b
except:
    print("The variable has not been assigned")

The variable has not been assigned

In [ ]:
a = b

NameError: name 'b' is not defined

In [ ]:
try:
    a = b
except NameError as ex:
    print(ex)

name 'b' is not defined

In [ ]:
## other kind of Exception
try:
    result = 1/0
except ZeroDivisionError as ex:
    print(ex)
    print("Please enter the denominator greater than zero")

division by zero
Please enter the denominator greater than zero

In [ ]:
## if we don't know which error may be happened (with the class of exception)
try:
    result = 1/2
    a = b
except ZeroDivisionError as ex:
    print(ex)
    print("Please enter the denominator greater than zero")
except Exception as ex1:
    print(ex1)
    print("Main exception got caught here")

name 'b' is not defined
Main exception got caught here

In [ ]:
try:
    num = int(input("Enter a number"))
    result = 10/num
except ValueError:
    print("this is not a valid number")
except ZeroDivisionError:
    print("enter demoninatot greater than 0")
except Exception as ex:
    print(ex)

In [ ]:
## try, except, else block

try:
    num = int(input("Enter a number"))
    result = 10/num
except ValueError:
    print("this is not a valid number")
except ZeroDivisionError:
    print("enter demoninatot greater than 0")
except Exception as ex:
    print(ex)
else:
    print(f"the result is {result}")

the result is 2.0

In [ ]:
## try, except, else, and finally block

try:
    num = int(input("Enter a number"))
    result = 10/num
except ValueError:
    print("this is not a valid number")
except ZeroDivisionError:
    print("enter demoninatot greater than 0")
except Exception as ex:
    print(ex)
else:
    print(f"the result is {result}")
finally:
    print("Execution complete.")

enter demoninatot greater than 0
Execution complete.

In [ ]:
### file handeling and Exception handeling

try:
    file = open('example1.txt', 'r')
    content = file.read()
    a = b
    print(content)

except FileNotFoundError:
    print("the file does not exist")
except Exception as ex:
    print(ex)
finally:
    if 'file' in locals() and not file.closed:
        file.close()
        print('file close')

name 'b' is not defined
file close

## Classes and Objects

In [ ]:
## example

class Car:
    pass

audi = Car()
bmw = Car()

In [ ]:
print(type(audi))

<class '__main__.Car'>

In [ ]:
print(audi)

<__main__.Car object at 0x0000016EF0DE6480>

In [ ]:
audi.windows = 4
print(audi.windows)

4

In [ ]:
tata = Car()
tata.doors = 4
print(tata.windows)

AttributeError: 'Car' object has no attribute 'windows'

In [ ]:
dir(tata)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'doors']

In [ ]:
## Instance variable and method

class Dog:
    ## constructor
    def __init__(self, name, age):
        self.name = name
        self.age = age

## create objects
dog1 = Dog("Buddy", 3)
print(dog1)
print(dog1.name)
print(dog1.age)

<__main__.Dog object at 0x0000016EF0DD35F0>
Buddy
3

In [ ]:
dog2 = Dog("Joy", 5)
print(dog2.name)
print(dog2.age)

Joy
5

In [ ]:
## define a class with instance methods

class Dog:
    ## constructor
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def bark(self):
        print(f"{self.name} says woof")

dog1 = Dog("Buddy", 3)
dog1.bark()
dog2 = Dog("lucy", 4)
dog2.bark()

Buddy says woof
lucy says woof

In [ ]:
## Modeling a Bank Account

## define a class for Bank account

class BankAccount:
    def __init__(self, owner, balance = 0):
        self.owner = owner
        self.balance = balance

    def deposit(self, amount):
        self.balance += amount
        print(f"{amount} is deposited. New balace is {self.balance}")

    def withdraw(self, amount):
        if amount > self.balance:
            print("Insufficient funds!")
        else:
            self.balance -= amount
            print(f"{amount} is withdrawn. New balance is {self.balance}")
    def get_balance(self):
        return self.balance


## create a acount

account = BankAccount("Ali", 5000)
print(account)

<__main__.BankAccount object at 0x0000016EF0DE6750>

In [ ]:
## call instance methods

account.deposit(1000)

1000 is deposited. New balace is 6000

In [ ]:
account.withdraw(3000)

3000 is withdrawn. New balance is 3000

In [ ]:
print(account.get_balance())

3000

### Inheritance in Python

In [ ]:
## Inheritance
## Parent class

class Car:
    ## constructors
    def __init__(self, windows, doors, enginetype):
        self.windows = windows
        self.doors = doors
        self.enginetype = enginetype

    ## instance method
    def drive(self):
        print(f"The person will drive the {self.enginetype} car")

In [ ]:
car1 = Car(4,5, "petrol")
car1.drive()

The person will drive the petrol car

In [ ]:
class Tesla(Car):
    ## constructors
    def __init__(self, windows, doors, enginetype, is_selfdriving):
        super().__init__(windows, doors, enginetype)
        self.is_selfdriving = is_selfdriving

    # instance method
    def selfdriving(self):
        print(f"Tesla supports self driving: {self.is_selfdriving}")

In [ ]:
tesla1 = Tesla(4,5, "electric", True)
tesla1.selfdriving()

Tesla supports self driving: True

In [ ]:
tesla1.drive()

The person will drive the electric car

In [ ]:
## multiple inheritance
## when a class inherits from more than one base class.
## Base class 1
class Animal:
    ## constructors
    def __init__(self, name):
        self.name = name

    ## instance method
    def speak(self):
        print("Subclasses must implement this method")

## Base class 2
class Pet:
    ## constructors
    def __init__(self, owner):
        self.owner = owner

## Derived animal:
class Dog(Animal, Pet):
    def __init__(self, name, owner):
        Animal.__init__(self, name)
        Pet.__init__(self, owner)

    def speak(self):
        return f"{self.name} says woof"
        

## create an object
dog = Dog("Boddy", "John")
print(dog.speak())
print(dog.speak())
print(f"Owner: {dog.owner}")

Boddy says woof

## Polymorphism

### Overriding

In [ ]:
## Base Class
class Animal:
    def speak(self):
        return "Sound of the animal"

## Derived Class 1
class Dog(Animal):
    def speak(self):
        return "Woof!"

## Derived class 2
class Cat(Animal):
    def speak(self):
            return "Mieeeu!"

## Function that demonstrates ploymorphism
def animal_speak(animal):
     print(animal.speak())


dog = Dog()
cat = Cat()
print(dog.speak())
print(cat.speak())
animal_speak(dog)

Woof!
Mieeeu!
Woof!

In [ ]:
## Polymorphism with function and methods

# base class
class Shape:  ## Shap is the name of class
    def area(self):
        return "The area of the figure"

## Derived class 1
class Rectangle(Shape):
    def __init__(self, width,height):
        self.width = width
        self.height = height

    def area(self):
        return self.height * self.width

## Derived class 2
class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return 3.14 * self.radius * self.radius

## function that demonsterate ploymorphism

def print_area(shape):  ## shape is the name of paramater 
    print(f"the shape is {shape.area()}")

rectangle = Rectangle(4,5)
circle = Circle(3)

## call the area function
print_area(rectangle)
print_area(circle)

the shape is 20
the shape is 28.259999999999998

In [ ]:
## interfaces
## Polymorphism with abstract base classes(ABC)

from abc import ABC, abstractmethod

## Define an abstract class
class Vehicle(ABC):
    @abstractmethod
    def start_engine(self):
        pass

## Derived class 1
class Car(Vehicle):
    def start_engine(self):
        return "Car engine started"

## Derived class 2
class Motorcycle(Vehicle):
    def start_engine(self):
        return "Motorcycle engine started"

## function that demonstrates polymorphism
def start_vehicle(vehicle):
    print(vehicle.start_engine())

## create objects of car and motocycle

car = Car()
motorcycle = Motorcycle()

start_vehicle(car)
start_vehicle(motorcycle)

Car engine started
Motorcycle engine started

## Encapsulation

In [ ]:
## Encapsulation with getter and setter methods

## public, protected, private variables or access modifiers

class Person:
    def __init__(self, name, age):
        self.name = name  ## public variable
        self.age = age  ## public variable

def get_name(person):
    return person.name

person = Person("Ali", 43)
print(person.name)
get_name(person)

Ali

'Ali'

In [ ]:
## protected variable
class Person:
    def __init__(self, name, age, gender):
        self.__name = name  ## private variable
        self.__age = age  ## private variable
        self.gender = gender

def get_name(person):
    return person.__name
person = Person("ALI", 33, "Male")
get_name(person)

AttributeError: 'Person' object has no attribute '__name'

In [ ]:
person = Person("ALI", 33, "Male")
dir(person)

['_Person__age',
 '_Person__name',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'gender']

In [ ]:
## protected variable
class Person:
    def __init__(self, name, age, gender):
        self._name = name  ## protected variable
        self._age = age  ## protected variable
        self.gender = gender

class Emplyee(Person):
    def __init__(self,name,age,gender):
        super().__init__(name,age,gender)

employee = Emplyee("Alireza", 33, "Male")
print(employee._name)

Alireza

In [ ]:
## Encapsulation with getter and setter
class Person:
    def __init__(self,name,age):
        self.__name = name ## private access modifier or variable 
        self.__age = age  ## private variable

    ## getter method for me
    def get_name(self):
        return self.__name

    ## setter method for name
    def set_name(self, name):
        self.__name = name

    ## getter method for age
    def get_age(self):
        return self.__age
    
     ## setter method for age
    def set_age(self, age):
        if age > 0:
            self.__age = age
        else:
            print("Age can not be negative")

person = Person("John", 25)

## access and modify private variables using gtter and setter

print(person.get_name())
print(person.get_age())

person.set_age(35)
print(person.get_age())

person.set_age(-5)

person.set_name("Robert")
print(person.get_name())

John
25
35
Age can not be negative
Robert

### Abstraction

In [ ]:
from abc import ABC, abstractmethod

## Abstract class
class Vehicle(ABC):
    def drive(self):
        print("The vehicle is used for driving")

    @abstractmethod
    def start_engine(self):
        pass

class Car(Vehicle):
    def start_engine(self):
        print("Car engine started")

def operate_vehicle(vehicle):
    vehicle.start_engine()
    vehicle.drive()

car = Car()
operate_vehicle(car)

Car engine started
The vehicle is used for driving

## Magic methodes

In [ ]:
class Person:
    pass

person = Person()
dir(person)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

In [ ]:
print(person)

<__main__.Person object at 0x0000016EF0B8B920>

In [ ]:
## basics method
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

person = Person("Ali", 32)
print(person)

<__main__.Person object at 0x0000016EF1FA3DA0>

In [ ]:
## basics method
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return f"{self.name}, {self.age} years old"

    def __repr__(self):
        return f"Person(name = {self.name}, age = {self.age})"

person = Person("Ali", 32)
print(person)
print(repr(person))

Ali, 32 years old
Person(name = Ali, age = 32)

## Custom excepteion(Raise and Throw an exception)

In [ ]:
## how customize our Exception
class Error(Exception):
    pass

class dobException(Error):
    pass

In [ ]:
year = int(input("Enter the dob"))
age = 2024 - year

try:
    if age <= 30 and age >= 30:
        print("The age is valid. You can apply for the exam")
    else:
        raise dobException
except dobException:
    print("Sorry, your age should be grater than 20 or less than 30")

Sorry, your age should be grater than 20 or less than 30

## Operator overloading

In [ ]:
dir(person)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'age',
 'name']

In [ ]:
## Mathematical operation for vectors

class Vector:
    def __init__(self, x,y):
        self.x = x
        self.y = y

    def __add__(self, other):
        return Vector(self.x + other.x, self.y + other.y)
    
    def __sub__(self, other):
        return Vector(self.x -other.x, self.y - other.y)

    def __mul__(self, other):
            return Vector(self.x * other, self.y * other)

    def __eq__(self, other):
            return self.x == other.x and self.y == other.y

    def __eq__(self,other):
            return self.x == other.x and self.y == other.y

    def __repr__(self):
          return f"Vector({self.x}, {self.y})"


## craete objects of teh vector class
v1 = Vector(2,3)
v2 = Vector(4,5)

print(v1+v2)
print(v1-v2)
print(v1*3)

Vector(6, 8)
Vector(-2, -2)
Vector(6, 9)

In [ ]:
### Overloading Operators for Complex Numbers

class ComplexNumber:
    def __init__(self, real, imag):
        self.real = real
        self.imag = imag

    def __add__(self, other):
        return ComplexNumber(self.real + other.real, self.imag + other.imag)

    def __sub__(self, other):
        return ComplexNumber(self.real - other.real, self.imag - other.imag)

    def __mul__(self, other):
        real_part = self.real * other.real - self.imag * other.imag
        imag_part = self.real * other.imag + self.imag * other.real
        return ComplexNumber(real_part, imag_part)

    def __truediv__(self, other):
        denominator = other.real**2 + other.imag**2
        real_part = (self.real * other.real + self.imag * other.imag) / denominator
        imag_part = (self.imag * other.real - self.real * other.imag) / denominator
        return ComplexNumber(real_part, imag_part)

    def __eq__(self, other):
        return self.real == other.real and self.imag == other.imag

    def __repr__(self):
        return f"{self.real} + {self.imag}i"

# Create objects of the ComplexNumber class
c1 = ComplexNumber(2, 3)
c2 = ComplexNumber(1, 4)

# Use overloaded operators
print(c1 + c2)  
print(c1 - c2)  
print(c1 * c2) 
print(c1 / c2)  
print(c1 == c2)

3 + 7i
1 + -1i
-10 + 11i
0.8235294117647058 + -0.29411764705882354i
False

## Iterators

In [ ]:
my_list = [1,2,3,4,5,6]
for i in my_list:
    print(i)

1
2
3
4
5
6

In [ ]:
type(my_list)

list

In [ ]:
print(my_list)

[1, 2, 3, 4, 5, 6]

In [ ]:
## Iterator  (lazy coding)
iterator = iter(my_list)
print(type(iterator))

<class 'list_iterator'>

In [ ]:
iterator

In [ ]:
## Iterator through all the next

next(iterator)

StopIteration:

In [ ]:
iterator = iter(my_list)

In [ ]:
try:
    print(next(iterator))
except StopIteration:
    print("There are no elements in the iterator")

There are no elements in the iterator

In [ ]:
## String iterator
my_string = "Hello"
string_iterator = iter(my_string)

print(next(string_iterator))
print(next(string_iterator))
print(next(string_iterator))

H
e
l

## Generator

In [ ]:
def square(n):
   for i in range(3):
    return i**2

In [ ]:
square(3)

0

In [ ]:
## use generator

def square(n):
   for i in range(3):
    yield i**2

In [ ]:
square(3)

In [ ]:
a = square(3)
a

In [ ]:
next(a)

4

In [ ]:
for i in square(3):
    print(i)

0
1
4

In [ ]:
def square(n):
   for i in range(5):
    yield i**2

In [ ]:
for i in square(5):
    print(i)

0
1
4
9
16

In [ ]:
def my_generator():
    yield 1
    yield 2
    yield 3

In [ ]:
gen = my_generator()
gen

In [ ]:
next(gen)

1

In [ ]:
for val in gen:
    print(val)

2
3

In [ ]:
## practical: reading large files

def read_large_file(file_path):
    with open(file_path, 'r') as file:
        for line in file:
            yield line

In [ ]:
import os
os.getcwd()

'c:\\Users\\Gebruiker\\Documents\\python_mysql_practice_2026'

In [ ]:
file_path = 'large_file.txt'

for line in read_large_file(file_path):
    print(line.strip())

Nederland" redirects here. For other uses, see Nederland (disambiguation).
This article is about the constituent country. For the sovereign state, see Kingdom of the Netherlands. For the European part of the constituent country, see European Netherlands. For other uses, see Netherlands (disambiguation).
Netherlands
Nederland (Dutch)
Constituent country in the Kingdom of the Netherlands
Flag of Netherlands
Flag	Official seal of Netherlands
Coat of arms
Motto: Je maintiendrai (French)
("I will maintain")
Anthem: Wilhelmus (Dutch)
("William")
Duration: 1 minute and 5 seconds.1:05

European Netherlands on the globe
Netherlands in Europe
Municipalities in the Caribbean
Show all
Location of Netherlands (dark green)
– in Europe (light green & dark grey)
– in the European Union (light green)

Sovereign state	Kingdom of the Netherlands
Before independence	Spanish Netherlands
Act of Abjuration	26 July 1581
Peace of Münster	30 January 1648
United Kingdom of the Netherlands	16 March 1815
Liberation Day	5 May 1945
Kingdom Charter	15 December 1954
Caribbean reorganisation	10 October 2010
Capital
and largest city
Amsterdam[a]
52°22′N 4°53′E
Government seat	The Hague[a]
Official languages	Dutch
Recognised regional languages
West FrisianPapiamentoEnglish[b]
Minority languages
Dutch Low SaxonDutch Sign LanguageLimburgishSinte RomaniYiddish[c]
Ethnic groups (2024)
72.0% Dutch[d]
9.2% other European
2.5% Turkish
2.3% Moroccan
2.0% Indonesian
2.0% Surinamese
1.1% Dutch Caribbean
8.9% other[3]
Religion (2025)[4]
58% no religion
28% Christianity
16% Catholicism
12% Protestantism
6% Islam
7% other
Demonym(s)	Dutch
Government	Unitary parliamentary constitutional monarchy
• Monarch
Willem-Alexander
• Prime Minister
Rob Jetten
Legislature	States General
• Upper house
Senate
• Lower house
House of Representatives
European Parliament
• Netherlands constituency
31 seats
Area
• Total
41,865[5][e] km2 (16,164 sq mi) (134th)
• Water (%)
18.41[6]
Highest elevation (Mount Scenery[f])	870 m (2,850 ft)
Population
• 2026 census
Neutral increase 18,130,208[7] (70th)
• Density
541/km2 (1,401.2/sq mi) (26th)
GDP (PPP)	2026 estimate
• Total
Increase $1.599 trillion[8] (29th)
• Per capita
Increase $88,202[8] (10th)
GDP (nominal)	2026 estimate
• Total
Increase $1.424 trillion[8] (18th)
• Per capita
Increase $78,535[8] (10th)
Gini (2025)	Positive decrease 25.9[9]
low
HDI (2023)	Increase 0.955[10]
very high · 8th
Currency
Euro (€) (EUR)United States dollar (US$) (USD)[g]
Time zone
UTC+01:00 (CET)UTC−04:00 (AST)
[h]
• Summer (DST)
UTC+02:00 (CEST)UTC−04:00 (AST)
Date format	dd-mm-yyyy[i]
Calling code	+31, +599[j]
Internet TLD	.nl, .bq[k]
The Netherlands,[l] also informally known as Holland, is a country in Northwestern Europe, with overseas territories in the Caribbean. It is the largest of the four constituent countries of the Kingdom of the Netherlands.[12] The Netherlands consists of twelve provinces and three overseas special municipalities. European Netherlands has land borders with Germany to the east and with Belgium to the south, and a coastline to the north and west. It shares maritime borders with the United Kingdom, Germany, and Belgium in the North Sea.[13] The official language is Dutch, with West Frisian as a secondary official language in the province of Friesland.[1] Dutch, English, and Papiamento are official languages in the Caribbean territories.[1] People from the Netherlands are referred to as Dutch.[14]

Netherlands literally means "lower countries", in reference to its low elevation and flat topography, 26% of which is below sea level.[15] Most of the areas below sea level, known as polders, are the result of land reclamation that began in the 14th century.[16] The Dutch Republic experienced major political, economic, and cultural development; this period is commonly known as the Dutch Golden Age.[17] During this time, its trading companies, the Dutch East India Company and the Dutch West India Company, established multiple colonies and trading posts.[18][19] While neutral in the First World War, the Netherlands was invaded and occupied by Nazi Germany in 1940 during the Second World War, which lasted until the end of the war in 1945.

With a population of over 18 million people, all living within a total area of 41,850 km2 (16,160 sq mi)—of which the land area is 33,500 km2 (12,900 sq mi)—the Netherlands is the 15th most densely populated country, with a density of 433 people per square kilometre (1,120 people/sq mi). Nevertheless, it is the world's second largest exporter of food and agricultural products by value, owing to its fertile soil, mild climate, intensive agriculture, and inventiveness.[20][21][22] The four largest cities are Amsterdam, Rotterdam, The Hague and Utrecht.[23] Amsterdam is most populous city and the nominal capital, though the primary national political institutions are in The Hague.[24]

The Netherlands has been a parliamentary constitutional monarchy with a unitary structure since 1848. The country has a tradition of pillarisation (separation of citizens into groups by religion and political beliefs) and a long record of social tolerance, having legalised prostitution and euthanasia, along with maintaining a liberal drug policy. The Netherlands allowed women's suffrage in 1919 and was the first country to legalise same-sex marriage in 2001.[25] A developed country, its mixed-market advanced economy is the 18th-largest in the world and has the 11th-highest per capita income globally. The Hague holds the seat of the States General, cabinet, and Supreme Court.[26] The Port of Rotterdam is the busiest in Europe.[27] Schiphol is the busiest airport in the Netherlands and the fourth busiest in Europe. The Netherlands is a founding member of the European Union, eurozone, G10, NATO, OECD, and World Trade Organization, as well as a part of the Schengen Area and the trilateral Benelux Union. It hosts intergovernmental organisations and international courts, many of which are in The Hague.[28]

Etymology
Main article: Terminology of the Low Countries
Netherlands and the Low Countries
In most Romance languages, the term "Low Countries" is officially used as the name for the Netherlands. The countries that constitute the region called the Low Countries (Netherlands, Belgium, and Luxembourg) all have similar toponymy. Place names with Neder, Nieder, Nedre, Nether, Lage(r) or Low(er) (in Germanic languages) and Bas or Inferior (in Romance languages) are in use in low-lying places all over Europe. The Romans made a distinction between the Roman provinces of downstream Germania Inferior (nowadays part of Belgium and the Netherlands) and upstream Germania Superior. Thus, in the case of the Low Countries and the Netherlands, the geographical location of this lower region is more or less downstream and near the sea, compared to that of the upper region of Germania Superior. The designation 'low' returned in the 10th-century Duchy of Lower Lorraine, which covered much of the Low Countries.[29][30]

The Dukes of Burgundy used the term les pays de par deçà ("the lands over here") for the Low Countries.[31] Under Habsburg rule, this became pays d'embas ("lands down here").[32] This was translated as Neder-landen in contemporary Dutch official documents.[33] From a regional point of view, Niderlant was also the area between the Meuse and the lower Rhine in the late Middle Ages. From the mid-16th century, the "Low Countries" and the "Netherlands" lost their original deictic meaning.

Holland
The term Holland has frequently been used informally to refer to the whole of the modern country of the Netherlands in various languages,[34] including Dutch[35][36] and English. In some languages, Holland is used as the formal name for the Netherlands. However, Holland is a region within the Netherlands that consists of the two provinces of North and South Holland. Formerly these were a single province, and earlier the County of Holland, which also included parts of present-day Utrecht province. The emphasis on Holland during the formation of the Dutch Republic, the Eighty Years' War, and the Anglo-Dutch wars in the 17th and 18th centuries made Holland a pars pro toto for the entire country.[37][38]

Many Dutch people object to the country being referred to as Holland instead of the Netherlands, on much the same grounds as many Welsh or Scottish people object to the United Kingdom being referred to as England.[39] In particular, those from regions other than Holland find it undesirable or misrepresentative to use the term Holland for the whole country,[34] as the Holland region only comprises two of the twelve provinces, and 38% of Dutch citizens. As of 2019, the Dutch government officially has preferred the Netherlands over Holland when talking about the country.[40][41][42]

Often Holland or Hollanders are used by the Flemish to refer to the Dutch in the Netherlands.[43] The terms are used in a derogatory fashion [44][45] by the Dutch living south of the great rivers (a natural cultural, social, and religious boundary formed by the rivers Rhine and Meuse) to refer to the Dutch in the north.[44] In the southern province of Limburg, the term is used for the Dutch from the other 11 provinces.[45]

Dutch
Dutch is used in English as the adjective for the Netherlands, as well as the demonym. The origins of the word go back to proto-Germanic *þiudiskaz (Latinised into Theodiscus), meaning "popular" or "of the people", the origin of Old Dutch *thiudisc and Old English þeodisc, meaning "(of) the common (Germanic) people".[46] At first, the English language used Dutch to refer to any or all speakers of West Germanic languages. The term gradually came to be used more narrowly to refer to the West Germanic people with whom the English had the most contact.

## Decorators

In [ ]:
## function copy
## closure
## Decorators

In [ ]:
## function copy
def welcome():
    return "Welcome to the advanced python course"

welcome()

'Welcome to the advanced python course'

In [ ]:
wel = welcome
print(wel())
del welcome
print(wel())

Welcome to the advanced python course
Welcome to the advanced python course

In [ ]:
## closures functions

def main_welcome():
    msg = "Welcome"
    def sub_welcome_method():
        print("Wlcome to the advanced python course ")

        print("Please learn these econcepts properly")
    return sub_welcome_method()

In [ ]:
main_welcome()

Wlcome to the advanced python course
Please learn these econcepts properly

In [ ]:

def main_welcome():
    msg = "Welcome"
    def sub_welcome_method():
        print("Wlcome to the advanced python course ")
        print(msg)
        print("Please learn these econcepts properly")
    return sub_welcome_method()

In [ ]:
main_welcome()

Wlcome to the advanced python course
Welcome
Please learn these econcepts properly

In [ ]:
def main_welcome(msg):
    def sub_welcome_method():
        print("Wlcome to the advanced python course ")
        print(msg)
        print("Please learn these econcepts properly")
    return sub_welcome_method()

In [ ]:
main_welcome("Welcome every one")

Wlcome to the advanced python course
Welcome every one
Please learn these econcepts properly

In [ ]:
def main_welcome(func):
    def sub_welcome_method():
        print("Wlcome to the advanced python course ")
        func()
        print("Please learn these econcepts properly")
    return sub_welcome_method()

In [ ]:
main_welcome(print)

Wlcome to the advanced python course

Please learn these econcepts properly

In [ ]:
def main_welcome(func):
    def sub_welcome_method():
        print("Wlcome to the advanced python course ")
        func("Welcome every one to this tutorial")
        print("Please learn these econcepts properly")
    return sub_welcome_method()

In [ ]:
main_welcome(print)

Wlcome to the advanced python course
Welcome every one to this tutorial
Please learn these econcepts properly

In [ ]:
def main_welcome(func, lst):
    def sub_welcome_method():
        print("Wlcome to the advanced python course ")
        print(func(lst))
        print("Please learn these econcepts properly")
    return sub_welcome_method()

In [ ]:
main_welcome(len, [1,2,3,4,5])

Wlcome to the advanced python course
5
Please learn these econcepts properly

In [ ]:
## Decorator

def main_welcome(func):
    def sub_welcome_method():
        print("Wlcome to the advanced python course ")
        func()
        print("Please learn these econcepts properly")
    return sub_welcome_method()

In [ ]:
def course_introduction():
    print("This is an advanced python course")

course_introduction()

This is an advanced python course

In [ ]:
main_welcome(course_introduction)

Wlcome to the advanced python course
This is an advanced python course
Please learn these econcepts properly

In [ ]:
@main_welcome
def course_introduction():
    print("This is an advanced python course")

Wlcome to the advanced python course
This is an advanced python course
Please learn these econcepts properly

In [ ]:
## another example of Decorator
## closure means one function in another function

def my_decorator(func):
    def wrapper():
        print("Something is happening before the function is called.")
        func()
        print("Something is happening after the function is called.")
    return wrapper()

In [ ]:
@my_decorator
def say_hello():
    print("Hello!")

Something is happening before the function is called.
Hello!
Something is happening after the function is called.

In [ ]:
## Decorators with arguments

def repeat(n):
    def decorator(func):
        def wrapper(*args, **kwargs):
            for _ in range(n):
                func(*args, **kwargs)
        return wrapper
    return decorator

In [ ]:
@repeat(3)
def say_hello():
    print("Hello")

In [ ]:
say_hello()

Hello
Hello
Hello

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

## create series from list
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series :\n", series)
print(type(series))

Series :
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [ ]:
## Craete a Series from dictionary

data = {'a':1, 'b':2, 'c': 3}
series_dict = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
data = [10,20,30]
index = ['a', 'b', 'c']
pd.Series(data, index = index)

a    10
b    20
c    30
dtype: int64

In [ ]:
## Dataframe
## create a dataframe from a dictionary of list

data = {
    'Name': ['Alireza', 'john', 'Jack'],
    'Age': [25,54,18],
    'City':['Banglore', 'rome', 'Tokyo']
}

df = pd.DataFrame(data)
print(type(df))
print(df)

<class 'pandas.core.frame.DataFrame'>
      Name  Age      City
0  Alireza   25  Banglore
1     john   54      rome
2     Jack   18     Tokyo

In [ ]:
import numpy as np
np.array(df)

array([['Alireza', 25, 'Banglore'],
       ['john', 54, 'rome'],
       ['Jack', 18, 'Tokyo']], dtype=object)

In [ ]:
## Create a dataframe from a list of dictionary
data = [
    {'name':'Alireza', 'age': 32, 'city' : 'Bandlore' },
    {'name': 'John', 'age': 44, 'city': 'New York'},
    {'name': 'Jack', 'age': 36, 'city': 'Athen'},
    {'name': 'Marin', 'age':15, 'city':'London'}
]

df_list = pd.DataFrame(data)
print(type(df_list))
print(df_list)

<class 'pandas.core.frame.DataFrame'>
      name  age      city
0  Alireza   32  Bandlore
1     John   44  New York
2     Jack   36     Athen
3    Marin   15    London

In [ ]:
import pandas as pd
df_csv = pd.read_csv('sales_data.csv')
df_csv.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
df_csv.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
## Accessing data from dataframe
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal
...,...,...,...,...,...,...,...,...,...
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [ ]:
data = {
    'Name': ['Alireza', 'john', 'Jack'],
    'Age': [25,54,18],
    'City':['Banglore', 'rome', 'Tokyo']
}

df = pd.DataFrame(data)
print(type(df))
print(df)

<class 'pandas.core.frame.DataFrame'>
      Name  Age      City
0  Alireza   25  Banglore
1     john   54      rome
2     Jack   18     Tokyo

In [ ]:
df['Name']

0    Alireza
1       john
2       Jack
Name: Name, dtype: object

In [ ]:
type(df['Name'])

pandas.core.series.Series

In [ ]:
df.loc[0]

Name     Alireza
Age           25
City    Banglore
Name: 0, dtype: object

In [ ]:
df.iloc[0]

Name     Alireza
Age           25
City    Banglore
Name: 0, dtype: object

In [ ]:
data = {
    'Name': ['Alireza', 'john', 'Jack'],
    'Age': [25,54,18],
    'City':['Banglore', 'rome', 'Tokyo']
}

df = pd.DataFrame(data)
print(type(df))
print(df)

<class 'pandas.core.frame.DataFrame'>
      Name  Age      City
0  Alireza   25  Banglore
1     john   54      rome
2     Jack   18     Tokyo

In [ ]:
df.iloc[0,1]

25

In [ ]:
df.loc[0,'Age']

25

In [ ]:
df.iloc[0][0]

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_24840\2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Alireza'

In [ ]:
## iloc = Integer Location
df.iloc[0][1]

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_24840\1874938326.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]

25

In [ ]:
df.iloc[0][2]

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_24840\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Banglore'

In [ ]:
df.loc[2][2]

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_24840\678847361.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[2][2]

'Tokyo'

In [ ]:
## Accessing a specified element
df['Name']

0    Alireza
1       john
2       Jack
Name: Name, dtype: object

In [ ]:
df

      Name  Age      City
0  Alireza   25  Banglore
1     john   54      rome
2     Jack   18     Tokyo

In [ ]:
df.at[1,'Age']

54

In [ ]:
df.at[2,'Age']

18

In [ ]:
df.at[2,'Name']

'Jack'

In [ ]:
## Accessing a specified element using iat
df.iat[2,2]

'Tokyo'

In [ ]:
## Data manipulation with Dataframe
df

      Name  Age      City
0  Alireza   25  Banglore
1     john   54      rome
2     Jack   18     Tokyo

In [ ]:
df['Salary'] = [50000, 60000, 70000]
df

      Name  Age      City  Salary
0  Alireza   25  Banglore   50000
1     john   54      rome   60000
2     Jack   18     Tokyo   70000

In [ ]:
## remove a column
df.drop('Salary', axis= 1, inplace = True)

In [ ]:
df

      Name  Age      City
0  Alireza   25  Banglore
1     john   54      rome
2     Jack   18     Tokyo

In [ ]:
df

      Name  Age      City
0  Alireza   25  Banglore
1     john   54      rome
2     Jack   18     Tokyo

In [ ]:
## Add age to the column
df['Age'] = df['Age']+2

In [ ]:
df

      Name  Age      City
0  Alireza   27  Banglore
1     john   56      rome
2     Jack   20     Tokyo

In [ ]:
df.drop(0, inplace= True)

In [ ]:
df

   Name  Age   City
1  john   56   rome
2  Jack   20  Tokyo

In [ ]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [ ]:
print("Data type:\n", df.dtypes)

Data type:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In [ ]:
print("Statistical summary: \n", df.describe())

Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

### Data Manipulation and Analysis with Pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('data.csv')

## fetch the first five rows
df.head(5)

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [ ]:
df.tail()

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [ ]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [ ]:
## Handling missing values
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
12    False
13    False
14    False
15     True
16    False
17     True
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool

In [ ]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [ ]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [ ]:
df.fillna(0)   ## fillna  -- > na not available

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [ ]:
df_filled = df.fillna(0)

In [ ]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [ ]:
### filling the missing values with the mean of the column

df["Sales_fillna"] = df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product  Sales Region  Sales_fillna
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [ ]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
Sales_fillna    float64
dtype: object

In [ ]:
## renaming columns
df = df.rename(columns={'Date': 'Sales Date'})
df.head()

   Sales Date Category  Value   Product  Sales Region  Sales_fillna
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [ ]:
## change data types
df['Value_new'] = df['Value'].fillnaastype(float)
df.head()

   Sales Date Category  Value   Product  Sales Region  Sales_fillna  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0       28.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0       39.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0       32.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0        8.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0       26.0

In [ ]:
## change data types
df['Value_new'] = df['Value'].fillna(df['Value'].mean()).astype(int)
df.head()

   Sales Date Category  Value   Product  Sales Region  Sales_fillna  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0         28
1  2023-01-02        B   39.0  Product3  110.0  North         110.0         39
2  2023-01-03        C   32.0  Product2  398.0   East         398.0         32
3  2023-01-04        B    8.0  Product1  522.0   East         522.0          8
4  2023-01-05        B   26.0  Product3  869.0  North         869.0         26

In [ ]:
df['New value'] = df['Value'].apply(lambda x:x*2)
df.head()

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillna,Value_new,New value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

In [ ]:
## Data aggregartion and grouping
df.head()

,Sales Date,Category,Value,Product,Sales,Region,Sales_fillna,Value_new,New value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26,52.0

In [ ]:
grouped_mean = df.groupby('Product')['Value'].mean().astype(int)
print(grouped_mean)

Product
Product1    46
Product2    52
Product3    55
Name: Value, dtype: int32

In [ ]:
group_sum = df.groupby(['Product', 'Region'])['Value'].sum()
print(group_sum)

Product   Region
Product1  East      292.0
          North       9.0
          South     100.0
          West      246.0
Product2  East       56.0
          North     127.0
          South     181.0
          West      428.0
Product3  East      202.0
          North     203.0
          South     215.0
          West      373.0
Name: Value, dtype: float64

In [ ]:
group_mean = df.groupby(['Product', 'Region'])['Value'].mean()
print(group_mean)

Product   Region
Product1  East      41.714286
          North      4.500000
          South     50.000000
          West      82.000000
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     40.600000
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [429]:
## aggregate multiple function
grouped_agg = df.groupby('Region')['Value'].agg(['mean', 'sum', 'count'])
grouped_agg

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

In [432]:
## Merging and joining dataframes
## create sample dataframes
df1 = pd.DataFrame({'Key':['A','B', 'C'], 'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B', 'D'], 'Value1':[4,5,6]})

In [433]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [434]:
df2

  Key  Value1
0   A       4
1   B       5
2   D       6

In [435]:
## Merge dataframe on the "Key columns"
pd.merge(df1, df2,on = 'Key', how='inner')

  Key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [ ]:
pd.merge(df1, df2,on = 'Key', how='outer')  ## outer means full join

  Key  Value1_x  Value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0

In [437]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [438]:
df2

  Key  Value1
0   A       4
1   B       5
2   D       6

In [440]:
pd.merge(df1, df2,on = 'Key', how='left')

  Key  Value1_x  Value1_y
0   A         1       4.0
1   B         2       5.0
2   C         3       NaN

In [441]:
pd.merge(df1, df2,on = 'Key', how='right')

  Key  Value1_x  Value1_y
0   A       1.0         4
1   B       2.0         5
2   D       NaN         6